In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [19]:
X = np.array([[2, 5],
     [4, 2],
     [6, 3],
     [3, 4],
     [5, 1]])
n, p = X.shape

x_bars = X.mean(axis=0)

x_vars = X.var(axis=0)

S = np.cov(X, rowvar=False, bias=True)

X, n, p, x_bars, x_vars

(array([[2, 5],
        [4, 2],
        [6, 3],
        [3, 4],
        [5, 1]]),
 5,
 2,
 array([4., 3.]),
 array([2., 2.]))

In [39]:
var_vec = np.std(X,axis=0)

Z = (X - x_bars ) / var_vec

D_inv = np.diag(1/var_vec)

R = D_inv @ S @ D_inv
Z, R

(array([[-1.41421356,  1.41421356],
        [ 0.        , -0.70710678],
        [ 1.41421356,  0.        ],
        [-0.70710678,  0.70710678],
        [ 0.70710678, -1.41421356]]),
 array([[ 1. , -0.7],
        [-0.7,  1. ]]))

In [45]:
v, U = np.linalg.eig(R)

C = Z @ U
C

array([[-2.00000000e+00,  2.01751532e-16],
       [ 5.00000000e-01, -5.00000000e-01],
       [ 1.00000000e+00,  1.00000000e+00],
       [-1.00000000e+00,  1.00875766e-16],
       [ 1.50000000e+00, -5.00000000e-01]])