# PCA

In [51]:
import numpy as np
import pandas as pd


In [52]:
data = [
[1396, 90, 174, 850, 369, 166],
[1721, 92, 180, 965, 415, 169],
[1580, 83, 170, 970, 395, 170],
[1769, 90, 180, 1080, 440, 169],
[2068, 88, 180, 1135, 446, 170],
[1769, 90, 182, 1060, 424, 168],
[2986, 188, 226, 1510, 472, 175],
[2675, 177, 222, 1365, 469, 175],
[2548, 182, 226, 1350, 471, 180],
[1998, 122, 190, 1255, 473, 177],
[1905, 125, 194, 1120, 439, 171],
[1993, 115, 185, 1190, 451, 172],
[2494, 171, 208, 1300, 432, 164],
[1994, 160, 214, 1220, 439, 169],
[2933, 150, 200, 1345, 466, 176],
[1995, 120, 177, 1265, 436, 177],
[1952, 87, 144, 1430, 436, 169],
[2109, 112, 149, 1320, 457, 184],
[1117, 50, 135, 810, 371, 162],
[1116, 58, 145, 780, 364, 155],
[1580, 80, 159, 880, 370, 156],
[1294, 103, 189, 805, 370, 157],
[1461, 100, 181, 925, 363, 161],
[1294, 95, 184, 730, 350, 160]
]

df = pd.DataFrame(data, columns=["Cylinder","Power","Velocity","Weight","Length","Width"])

df

,Cylinder,Power,Velocity,Weight,Length,Width
0,1396,90,174,850,369,166
1,1721,92,180,965,415,169
2,1580,83,170,970,395,170
3,1769,90,180,1080,440,169
4,2068,88,180,1135,446,170
5,1769,90,182,1060,424,168
6,2986,188,226,1510,472,175
7,2675,177,222,1365,469,175
8,2548,182,226,1350,471,180
9,1998,122,190,1255,473,177


In [53]:
X = np.array(data)
X, X.shape

(array([[1396,   90,  174,  850,  369,  166],
        [1721,   92,  180,  965,  415,  169],
        [1580,   83,  170,  970,  395,  170],
        [1769,   90,  180, 1080,  440,  169],
        [2068,   88,  180, 1135,  446,  170],
        [1769,   90,  182, 1060,  424,  168],
        [2986,  188,  226, 1510,  472,  175],
        [2675,  177,  222, 1365,  469,  175],
        [2548,  182,  226, 1350,  471,  180],
        [1998,  122,  190, 1255,  473,  177],
        [1905,  125,  194, 1120,  439,  171],
        [1993,  115,  185, 1190,  451,  172],
        [2494,  171,  208, 1300,  432,  164],
        [1994,  160,  214, 1220,  439,  169],
        [2933,  150,  200, 1345,  466,  176],
        [1995,  120,  177, 1265,  436,  177],
        [1952,   87,  144, 1430,  436,  169],
        [2109,  112,  149, 1320,  457,  184],
        [1117,   50,  135,  810,  371,  162],
        [1116,   58,  145,  780,  364,  155],
        [1580,   80,  159,  880,  370,  156],
        [1294,  103,  189,  805,  

In [54]:
x_bar = np.mean(X,axis=0)
x_bar

array([1906.125     ,  113.66666667,  183.08333333, 1110.83333333,
        421.58333333,  168.83333333])

In [55]:
Y = X - x_bar
Y

array([[-5.10125000e+02, -2.36666667e+01, -9.08333333e+00,
        -2.60833333e+02, -5.25833333e+01, -2.83333333e+00],
       [-1.85125000e+02, -2.16666667e+01, -3.08333333e+00,
        -1.45833333e+02, -6.58333333e+00,  1.66666667e-01],
       [-3.26125000e+02, -3.06666667e+01, -1.30833333e+01,
        -1.40833333e+02, -2.65833333e+01,  1.16666667e+00],
       [-1.37125000e+02, -2.36666667e+01, -3.08333333e+00,
        -3.08333333e+01,  1.84166667e+01,  1.66666667e-01],
       [ 1.61875000e+02, -2.56666667e+01, -3.08333333e+00,
         2.41666667e+01,  2.44166667e+01,  1.16666667e+00],
       [-1.37125000e+02, -2.36666667e+01, -1.08333333e+00,
        -5.08333333e+01,  2.41666667e+00, -8.33333333e-01],
       [ 1.07987500e+03,  7.43333333e+01,  4.29166667e+01,
         3.99166667e+02,  5.04166667e+01,  6.16666667e+00],
       [ 7.68875000e+02,  6.33333333e+01,  3.89166667e+01,
         2.54166667e+02,  4.74166667e+01,  6.16666667e+00],
       [ 6.41875000e+02,  6.83333333e+01,  4.291

In [56]:
X_cov = np.cov(X, rowvar=False)
S_diag = np.diag(X_cov)

Z = Y / np.sqrt(S_diag)
Z

array([[-0.96631293, -0.61021053, -0.3602289 , -1.13262374, -1.27195714,
        -0.37018947],
       [-0.35067617, -0.55864344, -0.12227954, -0.63325609, -0.15924662,
         0.02177585],
       [-0.61776781, -0.79069534, -0.51886181, -0.61154445, -0.6430338 ,
         0.15243096],
       [-0.25975136, -0.61021053, -0.12227954, -0.13388843,  0.44548737,
         0.02177585],
       [ 0.30663446, -0.66177762, -0.12227954,  0.10493958,  0.59062352,
         0.15243096],
       [-0.25975136, -0.61021053, -0.04296308, -0.22073498,  0.05845762,
        -0.10887926],
       [ 2.04557153,  1.91657674,  1.70199895,  1.73331238,  1.21954686,
         0.80570649],
       [ 1.4564545 ,  1.63295776,  1.54336603,  1.10367489,  1.14697879,
         0.80570649],
       [ 1.2158826 ,  1.76187548,  1.70199895,  1.03853998,  1.1953575 ,
         1.45898203],
       [ 0.17403578,  0.21486286,  0.27430274,  0.62601887,  1.24373622,
         1.06701671],
       [-0.00213105,  0.29221349,  0.43293565,  0.

In [63]:
D = np.eye(24) / 23
R = Z.T @ D @ Z
R_df = pd.DataFrame(R, columns=["Cylinder","Power","Velocity","Weight","Length","Width"])
R_df

,Cylinder,Power,Velocity,Weight,Length,Width
0,1.000000,0.860976,0.693315,0.904934,0.864202,0.709059
1,0.860976,1.000000,0.893987,0.746079,0.688515,0.552280
2,0.693315,0.893987,1.000000,0.491420,0.531908,0.363234
3,0.904934,0.746079,0.491420,1.000000,0.917112,0.790915
4,0.864202,0.688515,0.531908,0.917112,1.000000,0.863814
5,0.709059,0.552280,0.363234,0.790915,0.863814,1.000000


In [70]:
eigenvalues, eigenvectors = np.linalg.eig(R)
eigenvectors

array([[ 0.44420193,  0.03396424, -0.40143238, -0.79860042,  0.05002484,
         0.01086252],
       [ 0.41449041,  0.42122241, -0.03956072,  0.30666494,  0.489717  ,
         0.56154982],
       [ 0.34354013,  0.66343624,  0.36993499,  0.00718484, -0.31990926,
        -0.45009675],
       [ 0.43032128, -0.25516926, -0.48446064,  0.47258912,  0.1231523 ,
        -0.52583568],
       [ 0.43020876, -0.29558404,  0.04398442,  0.16597153, -0.71184868,
         0.43742517],
       [ 0.37763281, -0.47831913,  0.68102742, -0.13135953,  0.36529141,
        -0.11879722]])

In [68]:
C = Z @ eigenvectors
C

array([[-1.98031246e+00,  3.13206360e-01,  5.19444538e-01,
        -1.15766864e-01,  3.98799200e-01, -1.07856961e-01],
       [-7.62120893e-01, -1.30105825e-01,  4.32250858e-01,
        -2.20705589e-01, -2.08674274e-01, -1.73447328e-03],
       [-1.26263558e+00, -4.25065109e-01,  4.59122747e-01,
        -1.68614661e-01,  1.85979390e-01, -1.95002975e-01],
       [-2.68055592e-01, -4.54911838e-01,  1.82465622e-01,
         2.72323437e-02, -5.98359864e-01, -2.77637569e-02],
       [ 1.76711295e-01, -6.23732523e-01, -6.31992862e-02,
        -3.21104235e-01, -6.21455359e-01, -1.28188412e-01],
       [-4.94022369e-01, -2.03235202e-01,  1.47878300e-01,
        -6.03136390e-02, -4.06649859e-01, -1.71571911e-01],
       [ 3.86255660e+00,  8.17797679e-01, -5.04723180e-01,
        -1.17901398e-01,  1.36070618e-01, -1.41283496e-01],
       [ 3.12664973e+00,  7.55193370e-01, -1.38535115e-02,
        -4.51521033e-02, -7.42857718e-03,  6.37939282e-02],
       [ 3.36720144e+00,  5.96414647e-01,  6.148